// <auto-generated />
using System;
using EstacionamentoMvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Estacionamento.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("EstacionamentoMvc.Models.MovimentoEstacionamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MinutosPermanencia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoInicial")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoPorHora")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorInicial")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorPago")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movimentos");
                });

            modelBuilder.Entity("EstacionamentoMvc.Models.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TarifaHora")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TarifaInicial")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tarifas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TarifaHora = 3.00m,
                            TarifaInicial = 5.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
